### ISSUE TITLE
Unit testing.

### ISSUE THREAD

**Issue by ctartamella** [ctartamella/reflutter#4]
This library is in bad need of proper testing.  Right now all we really have is the ability to code generate the example.

**Comment by gedw99** [comment]
are you going to generate the unit test for each user type ? Would be a cool smoke test to know the code gen is hanging together

**Comment by ctartamella** [comment]
I haven't thought about how yet.  Right now I'm toying with some
integration tests that bring together serialization, a mock API, and
Reflutter.
